export const BEST_PRACTICE_SCENARIO = {
  title: "酒店推荐策略发布后，下单转化率异常下降",
  release: "v3.8.0",
  metric: "酒店搜索 → 下单转化率",
  before: {
    conversionRate: "12.4%",
    recommendationWeight: "0.35",
  },
  after: {
    elapsed: "约 2 小时",
    conversionRate: "9.1%",
    absoluteDecline: "3.3 个百分点",
    relativeDecline: "26.6%",
    anomalyDuration: "超过 30 分钟",
    recommendationWeight: "0.55",
  },
  riskRule: {
    baselineWindow: "过去 7 日",
    declineThreshold: "15%",
    durationThreshold: "30 分钟",
    description: "酒店下单转化率相对过去 7 日基线下降 ≥15%，且持续 ≥30 分钟 → 识别为发布风险。",
  },
  hypotheses: [
    {
      id: "A",
      priority: "优先排查",
      title: "新版排序策略导致高价酒店曝光增加",
      summary: "新版刚修改酒店排序，而且异常紧跟发布出现。",
      rationale: "异常发生在版本发布后，本次发布又直接修改了酒店推荐排序策略，因此它与当前异常同时具备时间相关性、变更相关性和业务链路相关性，应当优先调查。",
      signals: ["发布时间相关", "变更相关", "业务链路相关"],
      result: "SUPPORTED",
    },
    {
      id: "B",
      priority: "同时排查",
      title: "库存/价格服务异常",
      summary: "服务异常也可能导致用户无法完成下单，需要排除。",
      rationale: "即使推荐排序正常，如果库存或价格接口异常，也可能导致用户看到错误价格、无法选择房型或无法正常完成下单，因此需要作为替代原因排查。",
      signals: ["系统服务"],
      result: "CONTRADICTED",
    },
    {
      id: "C",
      priority: "同时排查",
      title: "用户流量结构变化",
      summary: "如果当天用户构成变化，也可能拉低整体转化率。",
      rationale: "整体转化率下降可能不是产品能力下降，而是由低意向流量、新用户比例或渠道结构变化造成，因此需要排除“用户变了”这一可能。",
      signals: ["用户结构"],
      result: "CONTRADICTED",
    },
  ],
  evidence: [
    {
      source: "发布变更",
      summary: "推荐权重 0.35 → 0.55",
      finding: "v3.8.0 将个性化推荐权重从 0.35 提高至 0.55",
      conclusion: "支持可能原因 A",
      tone: "support",
    },
    {
      source: "业务指标",
      summary: "高价酒店曝光占比 31% → 52%",
      finding: "高价酒店 Top 10 曝光占比从 31% 上升至 52%",
      conclusion: "支持可能原因 A",
      tone: "support",
    },
    {
      source: "用户反馈",
      summary: "“推荐酒店太贵”等反馈明显增加",
      finding: "“推荐酒店太贵”等价格相关负面反馈明显增加",
      conclusion: "支持可能原因 A",
      tone: "support",
    },
    {
      source: "库存/价格服务",
      summary: "库存/价格服务运行正常",
      finding: "成功率 99.96%，P95 延迟无明显异常",
      conclusion: "反驳可能原因 B",
      tone: "contradict",
    },
    {
      source: "流量结构",
      summary: "新老用户比例和渠道结构无明显变化",
      finding: "新老用户比例与主要渠道分布均无显著变化",
      conclusion: "反驳可能原因 C",
      tone: "contradict",
    },
  ],
  diagnosis: "v3.8.0 提高个性化推荐权重后，高价酒店获得更多曝光，降低用户下单意愿，是本次转化率下降的主要原因。",
  recommendation: "将个性化推荐权重从 0.55 回滚至 0.35，恢复上一版本排序策略。",
  verification: {
    conversionRate: "9.1% → 12.0%",
    baseline: "12.4%",
    premiumExposure: "52% → 33%",
    premiumExposureBaseline: "31%",
    result: "验证通过 → 风险解除 → 调查关闭",
  },
  reasoning: {
    risk: {
      question: "为什么触发风险？",
      guidedWhy: "相对降幅和异常持续时间都超过团队预设标准，因此系统进入调查。",
      why: "因为下单转化率下降 3.3 个百分点（相对下降 26.6%），相对降幅已经超过团队预设的 15% 风险阈值，并持续超过 30 分钟。",
      source: "风险标准由业务团队提前设定，AI 负责发现异常后的调查。",
      basis: [
        "发布前 7 日基线转化率：12.4%",
        "发布后转化率：9.1%",
        "绝对下降：3.3 个百分点",
        "相对过去 7 日基线下降：26.6%",
        "团队预设规则：相对下降 ≥15%，且持续 ≥30 分钟",
      ],
    },
    hypothesisSet: {
      question: "为什么是这三个调查方向？",
      why: "三个原因不是随机生成的，而是分别对应发布变更、系统服务、用户结构三个常见调查方向。Agent 同时保留这些可能，再用证据逐个验证。",
      basis: [
        "发布变更：本次版本直接调整推荐排序策略",
        "系统服务：库存或价格异常也会阻断正常下单",
        "用户结构：流量质量变化也可能拉低整体转化率",
      ],
    },
    strategy: {
      question: "为什么越来越支持新版排序策略？",
      why: "多项独立证据形成了连续因果链：推荐权重提高后，高价酒店获得更多曝光，价格相关负面反馈随之增加，同时下单转化率下降。",
      chain: ["推荐权重提高", "高价酒店曝光增加", "价格负面反馈增加", "下单转化率下降"],
      basis: [
        "推荐权重：0.35 → 0.55",
        "高价酒店 Top 10 曝光：31% → 52%",
        "“推荐酒店太贵”等负面反馈明显增加",
        "下单转化率：12.4% → 9.1%",
      ],
    },
    exclusions: [
      {
        hypothesisId: "B",
        question: "为什么基本排除库存/价格服务？",
        why: "如果库存/价格服务是主要原因，通常应该伴随成功率下降、延迟升高或明显服务异常；当前没有观察到这些信号。",
        conclusion: "因此目前没有证据支持服务异常是主要原因，但不表示它在任何情况下都绝对不可能。",
        basis: ["库存/价格服务成功率：99.96%", "P95 延迟：无明显异常"],
      },
      {
        hypothesisId: "C",
        question: "为什么基本排除用户流量结构？",
        why: "如果转化率下降主要来自流量质量变化，通常会观察到新老用户占比或主要渠道结构明显变化；当前没有观察到这些变化。",
        conclusion: "因此当前证据不支持流量结构变化是主要原因。",
        basis: ["新老用户比例：无显著变化", "主要渠道分布：无显著变化"],
      },
    ],
    action: {
      question: "为什么优先建议回滚？",
      why: "当前最强证据指向本次推荐权重调整，而 0.35 是发布前已稳定运行的配置，因此回滚是当前证据下优先推荐的低风险处置方案。",
      qualifier: "回滚不是唯一正确方案，是否执行仍由业务负责人审批决定。",
      basis: ["变更范围小", "恢复路径明确", "可以快速验证当前根因判断", "相比继续在线修改新策略，风险更可控"],
    },
    verification: {
      question: "为什么认为问题已经恢复？",
      why: "回滚后，业务核心指标和中间行为指标同时向发布前状态恢复，因此可以判断风险已经解除。",
      implication: "这不仅说明业务恢复，也进一步增强了此前根因判断的可信度。",
      basis: [
        "下单转化率：9.1% → 12.0%，发布前基线为 12.4%",
        "高价酒店 Top 10 曝光：52% → 33%，发布前为 31%",
      ],
    },
  },
  summary: "ReleaseGuard AI 是一个发布风险调查与处置 Agent。当业务指标在发布后出现异常，它会自动发现风险、提出多个可能原因、调用业务工具寻找证据、排除错误方向、形成根因判断和处置建议，并在人工审批后继续验证业务是否恢复。",
} as const;

export const BEST_PRACTICE_SECTIONS = [
  "发生了什么？",
  "为什么系统发现了风险？",
  "Agent 为什么提出这些可能原因？",
  "Agent 如何寻找证据？",
  "Agent 如何从证据得到根因？",
  "为什么需要人工审批？",
  "执行后如何验证恢复？",
  "ReleaseGuard AI 完成了什么？",
] as const;
