// D1 migrations remain the deployment source of truth. These idempotent
// statements make local previews and newly provisioned bindings usable before
// the first request, without relying on browser storage.
export const investigationRuntimeSchema = [
  `CREATE TABLE IF NOT EXISTS releases (
    id text PRIMARY KEY NOT NULL,
    version text NOT NULL,
    platform text NOT NULL,
    released_at text NOT NULL,
    rollout_status text NOT NULL,
    rollout_percentage real NOT NULL,
    feature_flags_json text NOT NULL,
    changed_modules_json text NOT NULL,
    provenance text NOT NULL,
    created_at text NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS metric_buckets (
    id text PRIMARY KEY NOT NULL,
    metric_key text NOT NULL,
    bucket_start text NOT NULL,
    bucket_end text NOT NULL,
    granularity_minutes integer NOT NULL,
    numerator integer,
    denominator integer,
    value real NOT NULL,
    sample_size integer NOT NULL,
    platform text,
    app_version text,
    region text,
    user_type text,
    dimension_signature text NOT NULL,
    release_id text REFERENCES releases(id),
    provenance text NOT NULL,
    created_at text NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS risk_events (
    id text PRIMARY KEY NOT NULL,
    correlated_release_id text REFERENCES releases(id),
    metric_key text NOT NULL,
    status text NOT NULL,
    direction text NOT NULL,
    filters_json text NOT NULL,
    segment_signature text NOT NULL,
    detected_at text NOT NULL,
    first_breached_at text NOT NULL,
    last_breached_at text NOT NULL,
    observed_value real NOT NULL,
    baseline_value real NOT NULL,
    absolute_deviation real NOT NULL,
    relative_deviation real NOT NULL,
    sample_size integer NOT NULL,
    threshold_pct real NOT NULL,
    min_sample_size integer NOT NULL,
    required_consecutive_buckets integer NOT NULL,
    trigger_bucket_ids_json text NOT NULL,
    baseline_method text NOT NULL,
    baseline_point_count integer NOT NULL,
    trigger_signature text NOT NULL,
    provenance text NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS investigation_runs (
    id text PRIMARY KEY NOT NULL,
    incident_id text NOT NULL,
    risk_event_id text REFERENCES risk_events(id),
    release_id text REFERENCES releases(id),
    question text NOT NULL,
    provider text NOT NULL,
    model text NOT NULL,
    planner_type text DEFAULT 'DETERMINISTIC' NOT NULL,
    status text NOT NULL,
    current_iteration integer DEFAULT 0 NOT NULL,
    active_iteration_id text,
    lock_version integer DEFAULT 0 NOT NULL,
    stop_reason text,
    current_diagnosis_revision integer DEFAULT 0 NOT NULL,
    total_tokens integer DEFAULT 0 NOT NULL,
    error_message text,
    started_at text,
    completed_at text,
    created_at text NOT NULL,
    updated_at text NOT NULL
  )`,
  "CREATE UNIQUE INDEX IF NOT EXISTS releases_platform_version_unique ON releases (platform, version)",
  "CREATE INDEX IF NOT EXISTS releases_released_idx ON releases (released_at)",
  "CREATE UNIQUE INDEX IF NOT EXISTS metric_buckets_fact_unique ON metric_buckets (metric_key, bucket_start, dimension_signature)",
  "CREATE INDEX IF NOT EXISTS metric_buckets_metric_time_idx ON metric_buckets (metric_key, bucket_start)",
  "CREATE INDEX IF NOT EXISTS metric_buckets_release_idx ON metric_buckets (release_id)",
  "CREATE UNIQUE INDEX IF NOT EXISTS risk_events_trigger_unique ON risk_events (trigger_signature)",
  "CREATE INDEX IF NOT EXISTS risk_events_release_idx ON risk_events (correlated_release_id)",
  "CREATE INDEX IF NOT EXISTS risk_events_metric_detected_idx ON risk_events (metric_key, detected_at)",
  `CREATE TABLE IF NOT EXISTS tool_calls (
    id text PRIMARY KEY NOT NULL,
    run_id text NOT NULL REFERENCES investigation_runs(id) ON DELETE cascade,
    name text NOT NULL,
    arguments_json text NOT NULL,
    canonical_signature text NOT NULL,
    status text NOT NULL,
    proposed_action_id text,
    approval_id text,
    agent_iteration_id text,
    trigger_message_id text,
    cache_source_tool_call_id text,
    iteration integer NOT NULL,
    order_index integer NOT NULL,
    result_id text,
    requested_at text NOT NULL,
    started_at text,
    completed_at text
  )`,
  `CREATE TABLE IF NOT EXISTS tool_results (
    id text PRIMARY KEY NOT NULL,
    run_id text NOT NULL REFERENCES investigation_runs(id) ON DELETE cascade,
    tool_call_id text NOT NULL REFERENCES tool_calls(id) ON DELETE cascade,
    status text NOT NULL,
    output_json text,
    error_message text,
    retryable integer DEFAULT false NOT NULL,
    created_at text NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS evidence (
    id text PRIMARY KEY NOT NULL,
    run_id text NOT NULL REFERENCES investigation_runs(id) ON DELETE cascade,
    tool_result_id text NOT NULL REFERENCES tool_results(id) ON DELETE cascade,
    category text NOT NULL,
    statement text NOT NULL,
    source text NOT NULL,
    strength text NOT NULL,
    provenance text DEFAULT 'synthetic' NOT NULL,
    collected_at text NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS diagnoses (
    id text PRIMARY KEY NOT NULL,
    run_id text NOT NULL REFERENCES investigation_runs(id) ON DELETE cascade,
    root_cause text NOT NULL,
    summary text NOT NULL,
    causal_chain_json text NOT NULL,
    affected_metrics_json text NOT NULL,
    affected_segments_json text NOT NULL,
    validated_claims_json text NOT NULL,
    unvalidated_claims_json text NOT NULL,
    confidence text NOT NULL,
    severity text NOT NULL,
    recommended_action text NOT NULL,
    revision integer DEFAULT 1 NOT NULL,
    status text DEFAULT 'FINAL' NOT NULL,
    supersedes_diagnosis_id text,
    superseded_at text,
    created_at text NOT NULL,
    updated_at text DEFAULT '' NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS proposed_actions (
    id text PRIMARY KEY NOT NULL,
    run_id text NOT NULL REFERENCES investigation_runs(id) ON DELETE cascade,
    diagnosis_id text NOT NULL REFERENCES diagnoses(id) ON DELETE cascade,
    type text NOT NULL,
    status text NOT NULL,
    title text NOT NULL,
    arguments_json text NOT NULL,
    rationale text NOT NULL,
    revision integer DEFAULT 1 NOT NULL,
    supersedes_proposed_action_id text,
    superseded_at text,
    created_at text NOT NULL,
    updated_at text NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS approvals (
    id text PRIMARY KEY NOT NULL,
    run_id text NOT NULL REFERENCES investigation_runs(id) ON DELETE cascade,
    proposed_action_id text NOT NULL REFERENCES proposed_actions(id) ON DELETE cascade,
    status text NOT NULL,
    decision text,
    reason text,
    requested_by text NOT NULL,
    decided_by text,
    target_owner text,
    target_repo text,
    revision integer DEFAULT 1 NOT NULL,
    supersedes_approval_id text,
    withdrawn_at text,
    created_at text NOT NULL,
    decided_at text
  )`,
  `CREATE TABLE IF NOT EXISTS audit_events (
    id text PRIMARY KEY NOT NULL,
    run_id text NOT NULL REFERENCES investigation_runs(id) ON DELETE cascade,
    proposed_action_id text,
    approval_id text,
    tool_call_id text,
    type text NOT NULL,
    actor text NOT NULL,
    details_json text NOT NULL,
    created_at text NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS agent_iterations (
    id text PRIMARY KEY NOT NULL,
    run_id text NOT NULL REFERENCES investigation_runs(id) ON DELETE cascade,
    sequence integer NOT NULL,
    trigger text NOT NULL,
    planner_type text NOT NULL,
    status text NOT NULL,
    decision_type text,
    public_rationale text,
    started_at text NOT NULL,
    completed_at text
  )`,
  `CREATE TABLE IF NOT EXISTS hypotheses (
    id text PRIMARY KEY NOT NULL,
    run_id text NOT NULL REFERENCES investigation_runs(id) ON DELETE cascade,
    revision integer NOT NULL,
    statement text NOT NULL,
    status text NOT NULL,
    confidence text NOT NULL,
    support_score real DEFAULT 0 NOT NULL,
    contradiction_score real DEFAULT 0 NOT NULL,
    confidence_reason text NOT NULL,
    created_by text NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS hypothesis_evidence_links (
    id text PRIMARY KEY NOT NULL,
    run_id text NOT NULL REFERENCES investigation_runs(id) ON DELETE cascade,
    hypothesis_id text NOT NULL REFERENCES hypotheses(id) ON DELETE cascade,
    evidence_id text NOT NULL REFERENCES evidence(id) ON DELETE cascade,
    relation text NOT NULL,
    explanation text NOT NULL,
    linked_by text NOT NULL,
    created_at text NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS investigation_trace_events (
    id text PRIMARY KEY NOT NULL,
    run_id text NOT NULL REFERENCES investigation_runs(id) ON DELETE cascade,
    iteration_id text,
    sequence integer NOT NULL,
    type text NOT NULL,
    actor text NOT NULL,
    public_summary text NOT NULL,
    details_json text NOT NULL,
    created_at text NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS investigation_messages (
    id text PRIMARY KEY NOT NULL,
    run_id text NOT NULL REFERENCES investigation_runs(id) ON DELETE cascade,
    client_request_id text NOT NULL,
    role text NOT NULL,
    intent text NOT NULL,
    content text NOT NULL,
    cited_evidence_ids_json text NOT NULL,
    created_at text NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS diagnosis_evidence_links (
    id text PRIMARY KEY NOT NULL,
    run_id text NOT NULL REFERENCES investigation_runs(id) ON DELETE cascade,
    diagnosis_id text NOT NULL REFERENCES diagnoses(id) ON DELETE cascade,
    evidence_id text NOT NULL REFERENCES evidence(id) ON DELETE cascade,
    relationship text NOT NULL,
    created_at text NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS approval_snapshots (
    id text PRIMARY KEY NOT NULL,
    approval_id text NOT NULL REFERENCES approvals(id) ON DELETE cascade,
    run_id text NOT NULL REFERENCES investigation_runs(id) ON DELETE cascade,
    diagnosis_id text NOT NULL REFERENCES diagnoses(id) ON DELETE cascade,
    proposed_action_id text NOT NULL REFERENCES proposed_actions(id) ON DELETE cascade,
    revision integer NOT NULL,
    frozen_payload_json text NOT NULL,
    checksum text NOT NULL,
    lifecycle_status text NOT NULL,
    created_at text NOT NULL,
    withdrawn_at text
  )`,
  `CREATE TABLE IF NOT EXISTS runtime_commands (
    id text PRIMARY KEY NOT NULL,
    run_id text NOT NULL REFERENCES investigation_runs(id) ON DELETE cascade,
    client_request_id text NOT NULL,
    command_type text NOT NULL,
    result_reference text,
    created_at text NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS feedback_records (
    id text PRIMARY KEY NOT NULL,
    timestamp text NOT NULL,
    platform text NOT NULL,
    app_version text NOT NULL,
    region text NOT NULL,
    user_type text NOT NULL,
    content text NOT NULL,
    tags_json text NOT NULL,
    source text NOT NULL,
    source_reference text NOT NULL,
    search_text text NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS incident_documents (
    id text PRIMARY KEY NOT NULL,
    incident_id text NOT NULL,
    title text NOT NULL,
    content text NOT NULL,
    metadata_json text NOT NULL,
    source_document text NOT NULL,
    corpus_version text NOT NULL,
    content_hash text NOT NULL,
    created_at text NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS incident_chunks (
    id text PRIMARY KEY NOT NULL,
    document_id text NOT NULL REFERENCES incident_documents(id) ON DELETE cascade,
    incident_id text NOT NULL,
    title text NOT NULL,
    section text NOT NULL,
    content text NOT NULL,
    metadata_json text NOT NULL,
    search_text text NOT NULL,
    token_count integer NOT NULL,
    content_hash text NOT NULL,
    corpus_version text NOT NULL,
    embedding_model text NOT NULL,
    embedding_json text
  )`,
  `CREATE TABLE IF NOT EXISTS incident_chunk_terms (
    chunk_id text NOT NULL REFERENCES incident_chunks(id) ON DELETE cascade,
    term text NOT NULL,
    term_frequency integer NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS rag_index_versions (
    id text PRIMARY KEY NOT NULL,
    corpus_version text NOT NULL,
    embedding_model text NOT NULL,
    dimensions integer NOT NULL,
    chunker_version text NOT NULL,
    corpus_checksum text NOT NULL,
    status text NOT NULL,
    created_at text NOT NULL,
    activated_at text
  )`,
  "CREATE INDEX IF NOT EXISTS investigation_runs_incident_idx ON investigation_runs (incident_id)",
  "CREATE INDEX IF NOT EXISTS investigation_runs_created_idx ON investigation_runs (created_at)",
  "CREATE INDEX IF NOT EXISTS tool_calls_run_idx ON tool_calls (run_id)",
  "CREATE INDEX IF NOT EXISTS tool_calls_signature_idx ON tool_calls (run_id, canonical_signature)",
  "CREATE UNIQUE INDEX IF NOT EXISTS tool_calls_action_unique ON tool_calls (proposed_action_id)",
  "CREATE UNIQUE INDEX IF NOT EXISTS tool_results_call_unique ON tool_results (tool_call_id)",
  "CREATE INDEX IF NOT EXISTS tool_results_run_idx ON tool_results (run_id)",
  "CREATE INDEX IF NOT EXISTS evidence_run_idx ON evidence (run_id)",
  "CREATE INDEX IF NOT EXISTS evidence_result_idx ON evidence (tool_result_id)",
  "CREATE UNIQUE INDEX IF NOT EXISTS diagnoses_run_revision_unique ON diagnoses (run_id, revision)",
  "CREATE INDEX IF NOT EXISTS proposed_actions_run_idx ON proposed_actions (run_id)",
  "CREATE INDEX IF NOT EXISTS proposed_actions_diagnosis_idx ON proposed_actions (diagnosis_id)",
  "CREATE UNIQUE INDEX IF NOT EXISTS approvals_action_unique ON approvals (proposed_action_id)",
  "CREATE INDEX IF NOT EXISTS approvals_run_idx ON approvals (run_id)",
  "CREATE INDEX IF NOT EXISTS audit_events_run_idx ON audit_events (run_id, created_at)",
  "CREATE INDEX IF NOT EXISTS audit_events_action_idx ON audit_events (proposed_action_id)",
  "CREATE UNIQUE INDEX IF NOT EXISTS agent_iterations_run_sequence_unique ON agent_iterations (run_id, sequence)",
  "CREATE INDEX IF NOT EXISTS agent_iterations_run_idx ON agent_iterations (run_id)",
  "CREATE INDEX IF NOT EXISTS hypotheses_run_idx ON hypotheses (run_id, revision)",
  "CREATE UNIQUE INDEX IF NOT EXISTS hypothesis_evidence_unique ON hypothesis_evidence_links (hypothesis_id, evidence_id)",
  "CREATE INDEX IF NOT EXISTS hypothesis_evidence_run_idx ON hypothesis_evidence_links (run_id)",
  "CREATE UNIQUE INDEX IF NOT EXISTS investigation_trace_run_sequence_unique ON investigation_trace_events (run_id, sequence)",
  "CREATE UNIQUE INDEX IF NOT EXISTS investigation_messages_request_unique ON investigation_messages (run_id, client_request_id)",
  "CREATE INDEX IF NOT EXISTS investigation_messages_run_idx ON investigation_messages (run_id, created_at)",
  "CREATE UNIQUE INDEX IF NOT EXISTS diagnosis_evidence_unique ON diagnosis_evidence_links (diagnosis_id, evidence_id)",
  "CREATE UNIQUE INDEX IF NOT EXISTS approval_snapshots_approval_unique ON approval_snapshots (approval_id)",
  "CREATE UNIQUE INDEX IF NOT EXISTS approval_snapshots_run_revision_unique ON approval_snapshots (run_id, revision)",
  "CREATE UNIQUE INDEX IF NOT EXISTS runtime_commands_request_unique ON runtime_commands (run_id, command_type, client_request_id)",
  "CREATE INDEX IF NOT EXISTS feedback_records_filter_idx ON feedback_records (platform, app_version, timestamp)",
  "CREATE UNIQUE INDEX IF NOT EXISTS incident_documents_corpus_incident_unique ON incident_documents (corpus_version, incident_id)",
  "CREATE UNIQUE INDEX IF NOT EXISTS incident_chunks_corpus_hash_unique ON incident_chunks (corpus_version, content_hash)",
  "CREATE INDEX IF NOT EXISTS incident_chunks_incident_idx ON incident_chunks (incident_id)",
  "CREATE UNIQUE INDEX IF NOT EXISTS incident_chunk_terms_unique ON incident_chunk_terms (chunk_id, term)",
  "CREATE INDEX IF NOT EXISTS incident_chunk_terms_term_idx ON incident_chunk_terms (term)",
  "CREATE UNIQUE INDEX IF NOT EXISTS rag_index_versions_identity_unique ON rag_index_versions (corpus_version, embedding_model, chunker_version)",
] as const;
